$script = <<-SCRIPT
sudo sysctl -w vm.max_map_count=262144
sudo usermod -aG docker vagrant

docker run -d --restart=always --name mongo mongo:3

docker run -d --restart=always --name elasticsearch -e "http.host=0.0.0.0" -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5

docker run -d --restart=always --name graylog --hostname graylog-server --link mongo --link elasticsearch -p 9000:9000 -p 12201:12201 -p 1514:1514 -p 1514:1514/udp -e GRAYLOG_HTTP_EXTERNAL_URI="http://127.0.0.1:9000/" graylog/graylog:4.0

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 9000, host: 9000
#  config.vagrant.plugins = "vagrant-docker-compose"
  config.vm.provision :docker
#  config.vm.provision :docker_compose
  config.vm.provision "shell", inline: $script
  config.vm.hostname = "graylog"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = "observability-graylog"
  end

end
